version: "3.8"
services:
  mysql:
    image: mysql:8
    container_name: multi_tenant_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"  # Changed to avoid conflict with existing MySQL on host
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - tenant-net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - mysql
    networks:
      - tenant-net

networks:
  tenant-net:
    driver: bridge
